site_name: qablet_contracts
theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [qablet_contracts]

nav:
  - 'index.md'
  - 'Specifications':
    - 'specifications/timetable.md'
    - 'specifications/operations.md'
    - 'specifications/units.md'
    - 'specifications/snapper.md'
    - 'specifications/batch.md'
    - 'specifications/expressions.md'
  - 'Examples':
    - 'examples/bond.md'
    - 'examples/equity.md'
    - 'examples/rate.md'
